import './global.scss';
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

export const metadata = {
  title: 'Welcome to host',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
