name: PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title, linked issue, and checklist
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request && context.payload.pull_request.body) || '';
            const title = (context.payload.pull_request && context.payload.pull_request.title) || '';

            const failures = [];

            // Require Conventional Commit-like title
            const titleOk = /^(feat|fix|docs|chore|refactor|test|build|ci|perf|style)(\([^)]+\))?: .+/.test(title);
            if (!titleOk) {
              failures.push('PR title should follow Conventional Commits (e.g., "feat(host): ...").');
            }

            // Require a linked issue keyword in the body
            const linkedIssue = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i.test(body || '');
            if (!linkedIssue) {
              failures.push('Add a linked issue reference (e.g., "Closes #123").');
            }

            // Require key checklist items to be checked
            const required = [
              'Builds pass',
              'Tests added/updated',
              'Lint/format pass',
            ];
            for (const label of required) {
              const re = new RegExp(`- \\[x\\] .*${label}`, 'i');
              if (!re.test(body)) {
                failures.push(`Checklist item not checked: "${label}".`);
              }
            }

            if (failures.length) {
              core.setFailed(failures.join('\n'));
            } else {
              core.notice('PR hygiene checks passed.');
            }

